apiVersion: v1
kind: Service
metadata:
  name: heart-animation-service
  namespace: heart-animation
  labels:
    app: heart-animation
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: heart-animation