apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
  namespace: snake-game
  labels:
    app: snake-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      imagePullSecrets:
      - name: nexus-docker-secret # Tham chiếu đến Secret đã tạo
      containers:
      - name: snake-game
        image: 192.168.2.83:5000/docker/snake-game:0.0.1 # Image từ Nexus
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"