apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
  namespace: snake-game
  labels:
    app: snake-game
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8085
  selector:
    app: snake-game